### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/r-python-exercise1-shreyakolte#1]
Hi Shreya,

Great work on the assignment. Some minor feedback:

It's important to have authorship on all notebooks (first name, last name)
I would like to see some markdown formatting for the title and section headers (use "#" Title, and "##" Section titles).
These changes make the notebook more readable and shareable.

I am giving you full credit, contingent on you fixing these minor issues by September 15th.
-Greg

**Comment by shreyakolte** [comment]
Hello, I have updated the file according to the feedback given by you.

**Comment by Gchism94** [comment]
This looks good. Next time, please close the issue when you believe that you have addressed it. 
-Greg
